name: "Syeef Karim - Graphic Development"
description: "Documenting the twists and turns it takes me to reach the start of my career"

url: "http://syeef.github.io/website/"

markdown: rdiscount
permalink: pretty